test: did precompile DOS attack
Watr-Protocol/watr pull request #158
Opened 2023-09-26 10:43 UTC by Moliholy

2023-09-26 15:54 UTC, peterwht requested changes
Looks great to me! Just a couple reverts to the explicit type declaration and it's good to merge.

2023-09-27 10:22 UTC, Moliholy commented on precompiles/did/src/lib.rs
> +		let mut services = BoundedVec::with_bounded_capacity(raw_services.len());
Added clarifying comment regarding the maximum capacity in [49f7f3f](https://github.com/Watr-Protocol/watr/pull/158/commits/49f7f3f6943211523a147538c15c169c92d8fa56).

2023-09-27 10:22 UTC, Moliholy commented on precompiles/did/src/lib.rs
> +		let mut services = BoundedVec::with_bounded_capacity(service_details.len());
Added clarifying comment regarding the maximum capacity in [49f7f3f](https://github.com/Watr-Protocol/watr/pull/158/commits/49f7f3f6943211523a147538c15c169c92d8fa56).

2023-09-27 10:22 UTC, Moliholy commented
I also opened an issue requesting a better interface for `BoundedVec` in https://github.com/paritytech/parity-common/issues/791.

2023-09-27 15:30 UTC, peterwht approved these changes

2023-09-28 09:42 UTC, merged