Issuer and CredentialTypes extrinsics
Watr-Protocol/watr pull request #48
Opened 2023-02-13 15:58 UTC by lana-shanghai

2023-02-13 16:40 UTC, NachoPal requested changes

2023-02-13 16:40 UTC, NachoPal commented on pallets/did/src/lib.rs
> +			Issuers::<T>::insert(issuer.clone(), IssuerInfo { status: IssuerStatus::Active });
Need to check if the Issuer already exist. If already exists then throw an error. Becase of this I realised we need an `activate_issuer` to give the possibility to set back to `Active` revoked Issuers

2023-02-13 16:40 UTC, NachoPal commented on pallets/did/src/lib.rs
> +		pub fn do_delete_issuer(issuer: DidIdentifierOf<T>) -> DispatchResult {
Check the Issuer exists and if its status is `Revoked`. We do not allow deleting `Active` Issuers.
Throw two different errors for each case

2023-02-13 16:40 UTC, NachoPal commented on pallets/did/src/lib.rs
> +			let pos = credentials_types.len();
`pos` should be the location returned by the `binary_search` to keep the vector ordered, not the last position (`.len()`)

2023-02-13 16:40 UTC, NachoPal commented on pallets/did/src/lib.rs
> +			credential: CredentialOf<T>,
Can you check if extrinsic fails when Credential type string length is exceeded? I am not sure. Maybe better to let it as unbounded Vec and check range when received

2023-02-13 16:40 UTC, NachoPal commented on pallets/did/src/lib.rs
> +			Self::deposit_event(Event::CredentialTypeAdded);
Please add the credential type added, it can be useful for the Indexing Service

2023-02-13 16:40 UTC, NachoPal commented on pallets/did/src/lib.rs
> +			match credentials_types.binary_search(&credential) {
duplicated `binary_search`

2023-02-13 16:40 UTC, NachoPal commented on pallets/did/src/lib.rs
> +			Self::deposit_event(Event::CredentialTypeRemoved);
Add Credential type removed to the event

2023-02-13 16:40 UTC, NachoPal commented on pallets/did/src/lib.rs
> +		) -> bool {
Following previous comment about location return by `binary_search`, probably modify the method to return a `Result` with that location index.

2023-02-13 16:40 UTC, NachoPal commented on pallets/did/src/types.rs
> +	New,
When is going to be used `New`? Why we need it?

2023-02-13 17:30 UTC, lana-shanghai commented on pallets/did/src/lib.rs
> +			Issuers::<T>::insert(issuer.clone(), IssuerInfo { status: IssuerStatus::Active });
Agree, it is best to separate the creation of a completely new user and a re-activation

2023-02-22 11:29 UTC, NachoPal requested changes

2023-02-22 11:29 UTC, NachoPal commented on pallets/did/src/lib.rs
> +			Issuers::<T>::remove(issuer);
This method is dangerous as there are not any checks inside. Add the logic for deleting the issuer inside it.

2023-02-22 11:29 UTC, NachoPal commented on pallets/did/src/lib.rs
> +				Ok(_pos) => (),
```suggestion
						let pos = credentials_types.binary_search(&credentials).err().ok_or(Error::<T>::CredentialAlreadyAdded)?;
						credentials_types
							.try_insert(pos, credential.clone())
							.map_err(|_| Error::<T>::MaxCredentials)?;
					}
```

2023-02-22 11:29 UTC, NachoPal commented on pallets/did/src/lib.rs
> +			}
```suggestion
let pos = credentials_types.binary_search(&credentials).ok().ok_or(Error::<T>::CredentialDoesNotExist)?;
credentials_types.remove(pos);
```

2023-02-22 11:29 UTC, NachoPal commented on pallets/did/src/types.rs
> +	New,
> Regarding the New status, I was thinking, can there be a situation when we mutate a storage and it falls back on a Default value Active which gives more rights than a blank New status. I can remove it as well.

Yeah, better remove it for now as I do not see a clear usage of it. I think for now `Active` and `Revoked` is enough.

2023-02-23 13:09 UTC, NachoPal requested changes

2023-02-23 13:09 UTC, NachoPal commented on pallets/did/src/lib.rs
>  			Ok(())
```suggestion
			})
```

2023-02-23 13:09 UTC, NachoPal commented on pallets/did/src/lib.rs
>  		pub fn delete_issuer(origin: OriginFor<T>, issuer: DidIdentifierOf<T>) -> DispatchResult {
```suggestion
		pub fn remove_issuer(origin: OriginFor<T>, issuer: DidIdentifierOf<T>) -> DispatchResult {
```
Just to be consistent with the rest of the extrinsics naming

2023-02-23 13:09 UTC, NachoPal commented on pallets/did/src/lib.rs
> +		pub fn do_delete_issuer(origin: OriginFor<T>, issuer: DidIdentifierOf<T>) -> DispatchResult {
```suggestion
		pub fn do_remove_issuer(origin: OriginFor<T>, issuer: DidIdentifierOf<T>) -> DispatchResult {
```
Just to be consistent with the rest of extrinsics naming

2023-02-23 13:09 UTC, NachoPal commented on pallets/did/src/lib.rs
> +			})?;
All this should be moved to `do_remove_issuer()`. `remove_issuer()` will call then `do_remove_issuer()`

2023-02-23 18:01 UTC, NachoPal approved these changes
#51 should be handled after #49 is merged. The reason of the dependancy is to make use of `ensure_controller()`

2023-02-24 08:39 UTC, merged