issuer related benchmarks
Watr-Protocol/watr pull request #69
Opened 2023-03-06 13:11 UTC by lana-shanghai

Solves #61

2023-03-09 18:09 UTC, peterwht commented on pallets/did/src/benchmarking.rs
> +		let mut credentials_types = BoundedVec::default();
Change this to a `Vec` instead of `BoundedVec`.

2023-03-09 18:09 UTC, peterwht commented on pallets/did/src/benchmarking.rs
> +			let mut credentials_types:
Remove this declaration from the for loop. `credential_types` is already declared in function scope, and this declaration within the loop scope will cause undesired results.

2023-03-09 18:09 UTC, peterwht commented on pallets/did/src/benchmarking.rs
> +		RawOrigin::Root, credentials_types.to_vec().clone()
```suggestion
		RawOrigin::Root, credentials_types.clone()
```
Not necessary if `credential_types` is changed to a `Vec`

2023-03-09 18:09 UTC, peterwht commented on pallets/did/src/benchmarking.rs
> +		let mut credentials_types = BoundedVec::default();
Change to `Vec`

2023-03-09 18:09 UTC, peterwht commented on pallets/did/src/benchmarking.rs
> +			let mut credentials_types:
Remove declaration from for loop

2023-03-09 18:09 UTC, peterwht commented on pallets/did/src/benchmarking.rs
> +		RawOrigin::Root, credentials_types.to_vec().clone()
Remove `to_vec()`

2023-03-09 18:16 UTC, peterwht commented on pallets/did/src/benchmarking.rs
> +		CredentialsTypes::<T>::put(credentials_types.clone());
This seems unnecessary as `add_credential_types` is what is being tested.

2023-03-09 18:17 UTC, peterwht commented on pallets/did/src/benchmarking.rs
> +		CredentialsTypes::<T>::put(credentials_types.clone());
This also seems wrong to store the credentials_types manually. They should be stored by the `add_credential_types`

2023-03-09 18:19 UTC, peterwht commented on pallets/did/src/benchmarking.rs
> +		assert_eq!(CredentialsTypes::<T>::get(), credentials_types);
Should verify that `CredentialsTypes` is empty.

2023-03-09 18:53 UTC, lana-shanghai commented on pallets/did/src/benchmarking.rs
> +		assert_eq!(CredentialsTypes::<T>::get(), Vec::default());
Left it as a `Vec::default()` as using a `BoundedVec` needs a separate types annotation. Benchmark works with both `Vec` and `BoundedVec`.

2023-03-10 11:48 UTC, NachoPal requested changes
- Pull, merge `pallet_did` and solve conflicts
- Reuse Peters method for creating credentials
- Add `assert_last_event` to your benchmarks `verify` (you can find examples in my benchmarks)
- Replace hardcoded weights in the extrinsics and return `DispatchResultWithPostInfo` for those weights that depends on variables

2023-03-13 11:41 UTC, NachoPal requested changes
Needs `fmt` and also need to run the benchmarks to update `devnet/src/weights/pallet_did.rs`

2023-03-13 11:41 UTC, NachoPal commented on pallets/did/src/lib.rs
> +			Ok(Some(T::WeightInfo::add_credentials_type(credentials_types.len().try_into().unwrap())).into())
No need `DispatchResultWithPostInfo` and no need to return any weight.

2023-03-13 11:41 UTC, NachoPal commented on pallets/did/src/benchmarking.rs
> +		CredentialsTypes::<T>::put(credentials_types.clone());
Instead of directly writing into the storage, better make a call to `DID::add_credential_types` to be consistent across the benchmarks.

2023-03-13 11:41 UTC, NachoPal commented on pallets/did/src/lib.rs
> +			Ok(Some(T::WeightInfo::remove_credentials_type(credentials_types.len().try_into().unwrap())).into())
No need `DispatchResultWithPostInfo` and no need to return any weight.

2023-03-13 12:04 UTC, NachoPal approved these changes

2023-03-13 13:25 UTC, merged