Feat/bn128 precompile
Watr-Protocol/watr pull request #9
Opened 2022-12-12 15:59 UTC by niall-watr

adds following precompiles
Bn128Add
Bn128Mul
Bn128Pairing
Blake2F

2022-12-13 11:19 UTC, NachoPal requested changes
Follow how weight tests where fixed here: https://github.com/paritytech/cumulus/pull/1601/files

2022-12-13 11:19 UTC, NachoPal commented on runtime/devnet/src/weights/block_weights.rs
> +			assert!(
To fix the weights tests compilation errors introduced by Weights V2, please follow what was done in Substrate and Cumulus: https://github.com/paritytech/cumulus/pull/1601/files

This is applicable to all weight files in this PR

2022-12-13 11:34 UTC, niall-watr commented on runtime/devnet/src/weights/block_weights.rs
> +			assert!(
Updated to use ref_time() in tests

2023-01-10 10:53 UTC, niall-watr commented
@NachoPal can we get this merged into main?

2023-01-10 13:46 UTC, merged